### PR TITLE
Allow import and export of opml files

### LINKED ISSUE #48: Feature: Add support for import of opml files
User can add podcasts only by searching for them in iTunes catalog and subscribing them manually. Option to import OPML files would allow user import all his podcasts with a single click.

### LINKED ISSUE #49: Feature: Add support for exporting podcasts
There is no way to export favorite (subscribed) podcast from Poddycast. As a result, when something happens, user can lose all his data. Option to export podcasts, in opml file for example, would allow the user back up his data.

### PR DESCRIPTION
**Pull request by EthanGrahn**
This branch includes the ability to import an opml file and automatically add valid urls to your favorites. The import uses a new Promise based request to validate and load the urls. This request function could be used to replace the current one in the future. The export function creates an opml file that includes the title and xmlUrl of the podcasts in your favorites list. Commit https://github.com/MrChuckomo/poddycast/commit/e2589b269f41f5f4aa8be0f3a17baf3df55cffb8 includes some simplification of global values where a function was being called when the values could be read directly. I am open to making any adjustments before this pull request is accepted. Closes #48. Closes #49.

### CODE REVIEW

**Comment by MrChuckomo** [comment]
The PR has been updated with the current state of the master.

**Comment by MrChuckomo** [comment]
@EthanGrahn I'm sorry that it takes so long to review your PR. 
Unfortunately there are some breaking changes.I need to resolve them first before merging back to `master`.

**Comment by EthanGrahn** [comment]
> @EthanGrahn I'm sorry that it takes so long to review your PR. 
> Unfortunately there are some breaking changes.I need to resolve them first before merging back to `master`. 

Not a problem. Let me know if you need any assistance from my end!

**Comment by MrChuckomo** [comment]
@EthanGrahn can you please attach some screenshots of the app. I would like to see how it looks on your end. Also a list of all the package versions you're using would be helpful. 

Unfortunately I get an error when opening the app: 

```json
Uncaught Error: Loading non-context-aware native module in renderer
```

**Comment by EthanGrahn** [comment]
@MrChuckomo yeah, I should have some to do that soon

**Comment by EthanGrahn** [comment]
image
image
Here are a couple images. Let me know if there are specific sections you need. These are my dependencies:
```
"dependencies": {
        "axios": "0.21.1",
        "xml2json": "0.12.0",
        "electron": "^11.2.1"
    },
    "devDependencies": {
        "electron-packager": "^14.2.1",
        "electron-rebuild": "2.3.4",
        "eslint": "^6.8.0"
    }
```

**Comment by EthanGrahn** [comment]
I cleared my npm_modules and the package-lock file and now I'm seeing the error you have. I'll do some investigation on my end.

**Comment by EthanGrahn** [comment]
It appears to be the `xml2json` package. I'll do a bit of rework on this to find a resolution.

**Comment by MrChuckomo** [comment]
Oh, thank you. That would be really great. 

I'm happy that we're able to reproduce the `error`.

**Comment by EthanGrahn** [comment]
@MrChuckomo Sorry for the delay! The latest commits should resolve the issue. I've also included the `package-lock.json` file as that seems to be the standard practice and should help us avoid package issues going forward.

**Review by MrChuckomo — APPROVED** [review]
@EthanGrahn - that looks really amazing. Thank you so much for this PR

**Pull request merged**
