### PR TITLE
Add volume slider

### PR DESCRIPTION
**Pull request by EthanGrahn**
Implemented a volume slider using exponential increase as detailed [here](https://www.dr-lex.be/info-stuff/volumecontrols.html#ideal3). I have also adjusted the css to display the player across the entire width to better accommodate the new volume slider.

### CODE REVIEW

**Comment by EthanGrahn** [comment]
Commit https://github.com/MrChuckomo/poddycast/pull/77/commits/b32f694f1bceec1a962299bb71d221d1298f40b8 resolves #74

**Comment by EthanGrahn** [comment]
Commit https://github.com/MrChuckomo/poddycast/pull/77/commits/b46de6db26c0f00580f173ee96b6a9c8ce615c56 resolves #56.  I also simplified the `speedUp()` and `speedDown()` functions to remove the switch statement.

**Comment by EthanGrahn** [comment]
I forgot to mention that with the merging of the settings file in the favorites file, I also included a feature that will automatically transfer users' current `addToInbox` settings into the favorites file.

**Comment by MrChuckomo** [comment]
@EthanGrahn - thank you so much for your contribution. That's really great work and you addressed some important issues. I appreciate that very much. 🙏

I'll check your pull-request in detail as soon as possible.

**Comment by MrChuckomo** [comment]
@EthanGrahn I just changed the volume icon (using https://material.io/resources/icons/?search=audio&style=baseline) to match with the overall app design.

**Pull request merged**
