### PR TITLE
Fix RSS Feed Parsing

### LINKED ISSUE #87: Podcasts found, favourited, but epsiodes not identified
A couple of podcasts are found. I favourite them. But no episodes are identified.

See images: 
Screenshot - 07_06_2021 , 11_21_59

Windows 10 Pro build 19041. x64 app version. Always-on VPN. Proxy mode not used.

Looking good - saves me disk space - but see bug above.

### PR DESCRIPTION
**Pull request by EthanGrahn**
Fixed issue where some feeds were not being parsed and would not display episodes as a result. There is also some initial work on simplifying the response parsing. The goal is to have the response XML parsed into a usable JSON object immediately when received. There is still an included option to return the raw XML for backwards compatibility. I am also starting to move away from globally importing all of the JavaScript files in the `index.html` and instead only importing/requiring when necessary.

Closes #87

### CODE REVIEW

**Review by MrChuckomo — APPROVED** [review]

**Comment by MrChuckomo** [comment]
Hi @EthanGrahn, this is really great work. Thank you so much. It's amazing how fast the Podcast feeds load now, using this async approach! 😃 👍 

Two little remarks before merging this back to the main:

1. I'm not so sure about the backward compatibility. Existing feeds doesn't seem to load. However, after I subscribed to them again, it's really fast. So, it's not a big deal actually. 
2. Episodes (of these new subscribed Podcasts) do not play on my side. Can you please check and confirm on your side? It doesn't matter where I try to play the episode - from the episodes list or directly from a specific Podcast feed. But existing episodes, from *old* Podcast feeds still playing. I couldn't quite figure out if the episode URL is also handled via these *promises*, and if this causes some problems with the actual audio playback.

**Comment by EthanGrahn** [comment]
Thanks for the feedback! I'll look into those issues and update here with what I find.

**Comment by EthanGrahn** [comment]
I've discovered the issue and I'm currently working to resolve it!

**Comment by EthanGrahn** [comment]
@MrChuckomo I made some fixes and it is good to test again. The old links should now work properly. There are some additional changes included in the last commit to ensure that invalid links are still marked correctly and that searching with text or a feed url still works.

**Comment by MrChuckomo** [comment]
That looks really good. That's great work. Thank you so much.

**Pull request merged**
